<?php

return [
    'linkedin' => [
        'label' => 'LinkedIn Recruiter',
        'category' => 'sourcing',
        'icon' => '💼',
        'description' => 'Sourcing automatique de profils LinkedIn',
        'token_label' => 'Token API LinkedIn Recruiter',
        'placeholder' => 'lir_xxxxxxxxxxxxxxxxxxxxxxxxxx',

        'env_key' => 'LINKEDIN_API_TOKEN',
        'test_url' => 'https://api.linkedin.com/v2/me',
        'docs_url' => 'https://developer.linkedin.com',
        'oauth' => false,
    ],
    'openai' => [
        'label' => 'Whisper / OpenAI',
        'category' => 'ai',
        'icon' => '🎙️',
        'description' => 'Transcription audio des entretiens (Whisper)',
        'token_label' => 'Clé API OpenAI',
        'placeholder' => 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

        'env_key' => 'OPENAI_API_KEY',
        'test_url' => 'https://api.openai.com/v1/models',
        'docs_url' => 'https://platform.openai.com',
        'oauth' => false,
    ],
    'anthropic' => [
        'label' => 'Claude API (Anthropic)',
        'category' => 'ai',
        'icon' => '🤖',
        'description' => 'Analyse IA centrale · Claude Sonnet 4',
        'token_label' => 'Clé API Anthropic',
        'placeholder' => 'sk-ant-xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        'env_key' => 'ANTHROPIC_API_KEY',
        'test_url' => null,
        'docs_url' => 'https://docs.anthropic.com',
        'oauth' => false,
    ],
    'indeed' => [
        'label' => 'Indeed Publisher',
        'category' => 'sourcing',
        'icon' => '🔎',
        'description' => 'Import de CVs depuis Indeed',
        'token_label' => 'Token API Indeed Publisher',
        'placeholder' => 'ind_pub_xxxxxxxxxxxxxxxxxxxx',
        'env_key' => 'INDEED_API_TOKEN',
        'test_url' => null,
        'docs_url' => 'https://developer.indeed.com',
        'oauth' => false,
    ],

    'apify' => [
        'label' => 'Apify',
        'category' => 'sourcing',
        'icon' => '🔎',
        'description' => 'Sourcing depuis des crawlers personnalisés',
        'token_label' => 'Token API Apify',
        'placeholder' => 'apify_xxxxxxxxxxxxxxxxxxxx',
        'env_key' => 'APIFY_API_TOKEN',
        'test_url' => 'https://api.apify.com/v2/actor-tasks',
        'docs_url' => 'https://apify.com/docs',
        'oauth' => false,
    ],
    'facebook' => [
        'label' => 'Facebook Jobs',
        'category' => 'sourcing',
        'icon' => '📘',
        'description' => 'Sourcing via Facebook Jobs',
        'token_label' => 'Token Facebook Graph API',
        'placeholder' => 'EAAGxxxxxxxxxxxxxxxxxxxx',
        'env_key' => 'FACEBOOK_API_TOKEN',
        'test_url' => null,
        'docs_url' => 'https://developers.facebook.com',
        'oauth' => false,
    ],
    'google_calendar' => [
        'label' => 'Google Calendar',
        'category' => 'scheduling',
        'icon' => '📅',
        'description' => 'Planification automatique des entretiens',
        'token_label' => 'OAuth Client ID',
        'placeholder' => 'xxxx.apps.googleusercontent.com',

        'env_key' => null,
        'test_url' => null,
        'docs_url' => 'https://developers.google.com/calendar',
        'oauth' => true,
    ],
    'zoom' => [
        'label' => 'Zoom',
        'category' => 'scheduling',
        'icon' => '📹',
        'description' => 'Import automatique des enregistrements Zoom',
        'token_label' => 'Server-to-Server Token',
        'placeholder' => 'eyJhbGciOiJSUzI1NiJ9...',
        'env_key' => 'ZOOM_API_TOKEN',
        'test_url' => null,
        'docs_url' => 'https://developers.zoom.us',
        'oauth' => false,
    ],
];
